---

version: '3'

services:
  api:
    env_file:
        "./api/.env"
    build:
      context: ./api
      dockerfile: ./Dockerfile
    image: "khaifahmi99/til-api"
    ports:
      - "9090:9090"
  
  web:
    env_file:
      "./client/.env"
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "khaifahmi99/til-client"
    ports:
      - "80:80"
    links:
      - "api:be"